### ISSUE TITLE
Script loop

### ISSUE THREAD

**Issue by preki** [mohlcyber/MISP-STIX-ESM#1]
Hi, 

I use a MISP v2.4.118 and script stuck in some kind of loop. 
A following message is repeating until I forced stop of the script: "STATUS: Could not find Events that are tagged with action:monitor:investigate".
I add a "exit ()" at the end of script and everything is fine now.
Please check.

Kind regards, 

Preki

**Comment by mohlcyber** [comment]
Hi Preki,

yes you are right. This script runs in an indefinite loop. The Idea was to use it as a monitoring script that is constantly running. You could put the script in a screen session and let it run forever. Or you use the script without a loop and with the exit you mentioned and create a cronjob to execute the script every few minutes. 

All the best,
Martin
