### ISSUE TITLE
Script execution error

### ISSUE THREAD

**Issue by preki** [mohlcyber/MISP-STIX-ESM#2]
Hi,

We have a error in script execution again, please find a error description bellow.
It looks a MISP upgrade cause this error, we are using MISP  v2.4.120 now.

ERROR: Error in __main__.main() - line 45 : write() argument must be str, not dict

Thanks.

**Comment by mohlcyber** [comment]
Hi Preki,
really strange. I just updated MISP to 2.4.120 to replicate the issue. I am not able to replicate the issue. 
Looks like it works on my end.
Could you please print out the variable 'stix' that you are trying to write to a file in line 45. Would be interesting to see what gets returned.
All the best,
Martin

**Comment by preki** [comment]
Lines 44-48:
stix = self.get_events(eid=eventid, format='stix')
                    with open(misp_path + 'misp_stix_{0}.xml'.format(str(eventid)), 'w') as esm_stix:
                        esm_stix.write(stix)
                        esm_stix.close()
                    print('SUCCESS: Successful exported the STIX file for event {0}.'.format(str(eventid)))

**Comment by mridderrtec** [comment]
I do have the exact same issue. I am also running MISP 2.4.120. It looks as if what is returned by:
stix = self.get_events(eid=eventid, format='stix')
is not in XML, but JSON and gets interpreted as a dictionary rather than a string. If you change:

esm_stix.write(stix) to esm_stix.write(str(stix)) 

it does no longer fail. But the resulting file cannot be consumed by ESM.

Bottomline: How to ensure that what is returned is STIX in XML and not JSON?

**Comment by mridderrtec** [comment]
Maybe this is the reason:

From the PyMISP changelog:

v2.4.120 (2020-01-17)
---------------------
.....
- Search with the STIX output returns a json STIX. [Raphaël Vinot]

  Was XML before.
.....

**Comment by mohlcyber** [comment]
Thanks mridderrtec, i will look into it. Will post any update here.

**Comment by mohlcyber** [comment]
I could replicate the issue and think it has to do something with an issue on the MISP API side. I also found another way how to retrieve the XML. So i could build a quick workaround if needed. Please let me know. 
I posted the issue here: https://github.com/MISP/MISP/issues/5618

**Comment by mohlcyber** [comment]
I updated the script which should solve the issue. I am using the rest api to export the stix not the pymisp libraries.
https://github.com/mohlcyber/MISP-STIX-ESM/blob/master/misp_stix.py

Please let me know if that solves the issue.

**Comment by mohlcyber** [comment]
Hi Guys, 
i will close the ticket for now. Please re-open if there are any issues.
All the best,
Martin

**Comment by preki** [comment]
Hi, 
there is an error in script line 40. 

Error log:

> ERROR: Error in __main__.main() - line 51 : HTTPSConnectionPool(host='misp.my.domainevents', port=443): Max retries exceeded with url: /restSearch (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7ff54dff92e8>: Failed to establish a new connection: [Errno -2] Name or service not known',))

Current:
`stix = requests.post(misp_url + 'events/restSearch', headers=self.headers, data=payload, verify=misp_verify)`

Should be:
`stix = requests.post(misp_url + '/restSearch', headers=self.headers, data=payload, verify=misp_verify)`

It's working form me after a correction.
